"""thumbnail

Revision ID: 004c5c874ae4
Revises: dbf9bb91c07e
Create Date: 2025-03-20 18:10:39.079559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '004c5c874ae4'
down_revision = 'dbf9bb91c07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_sermons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=500), nullable=True))
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_sermons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
