"""cornet

Revision ID: 2bfb688c6026
Revises: 004c5c874ae4
Create Date: 2025-03-25 14:26:23.951413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bfb688c6026'
down_revision = '004c5c874ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_devotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('theme', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('scripture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reflection', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('prayer', sa.Text(), nullable=False))
        batch_op.drop_column('devotion_date')
        batch_op.drop_column('scripture_reference')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_devotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('scripture_reference', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('devotion_date', sa.DATE(), nullable=False))
        batch_op.drop_column('prayer')
        batch_op.drop_column('reflection')
        batch_op.drop_column('scripture')
        batch_op.drop_column('theme')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
