"""empty message

Revision ID: 3407916ca936
Revises: 099cddd82813
Create Date: 2025-03-10 21:38:31.390399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3407916ca936'
down_revision = '099cddd82813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_of_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_image', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_of_month')
    # ### end Alembic commands ###
