"""blogs

Revision ID: 60d2ac889e7b
Revises: b935fb0356e0
Create Date: 2025-03-18 15:15:02.636123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d2ac889e7b'
down_revision = 'b935fb0356e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rhema_blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('date_published',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rhema_blogs', schema=None) as batch_op:
        batch_op.alter_column('date_published',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
