"""empty message

Revision ID: 765eac9aeaa2
Revises: a6a2501b129d
Create Date: 2025-05-08 01:08:00.981843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765eac9aeaa2'
down_revision = 'a6a2501b129d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Feedback')
    # ### end Alembic commands ###
