"""banner

Revision ID: b935fb0356e0
Revises: f370fc9b4b81
Create Date: 2025-03-18 13:20:43.240649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b935fb0356e0'
down_revision = 'f370fc9b4b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('banner_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('event_time')
        batch_op.drop_column('name')
        batch_op.drop_column('event_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('event_time', mysql.TIME(), nullable=False))
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('banner_image')
        batch_op.drop_column('date')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
