"""audio category

Revision ID: cc3fb9d9f3c5
Revises: 60d2ac889e7b
Create Date: 2025-03-19 23:48:33.141360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3fb9d9f3c5'
down_revision = '60d2ac889e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_sermons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_sermons', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
