"""thumbnail

Revision ID: dbf9bb91c07e
Revises: cc3fb9d9f3c5
Create Date: 2025-03-20 18:05:38.131135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf9bb91c07e'
down_revision = 'cc3fb9d9f3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_sermons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_sermons', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###
